version: 2

workflows:
  version: 2
  tests:
    jobs:
      - test
      - codecov:
          requires: [ test ]

jobs:
  test:
    docker:
      - image: circleci/golang:1.11.1
    environment:
      CGO_ENABLED: 0
    steps:
      - checkout
      - run:
          name: Running tests
          command: go test -v -coverprofile=coverage.txt -covermode=count
      - persist_to_workspace:
          root: .
          paths: [ coverage.txt ]
  codecov:
    docker:
       - image: plugins/codecov:2.0.3
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: codecov
